### PR TITLE
removed test that should be in ch5

### PR DESCRIPTION
**Pull request by oldfartdeveloper**
@milesfrain I've removed the first test that you asserted belonged in Chapter 5 (and I agree) and renumbered the tests.

I also tested your test suite by running the first exercise group, then adding the 2nd, and so forth through the last exercise group (4th).  Everything behaved as I expect it should.

The PR is to do what you were already going to do for your solutions branch.

### CODE REVIEW

**Comment by milesfrain** [comment]
Thanks for the PR.

I think there should be a note at the start of these tests to remind readers that the first exercise was moved to the tests in the previous chapter (even if they supposedly just tacked that exercise). ~~Would you update this PR with that note?~~

It would also be great if the exercise groups matched the chapter anchors. It looks like those are 0-indexed, so maybe this should be the scheme:
* "Exercise group 0" https://book.purescript.org/chapter6.html#exercises
* "Exercise group 1" https://book.purescript.org/chapter6.html#exercises-1
* ...

And that lines up with your renumbering anyway. We can apply this new scheme to the other chapters.

**Comment by milesfrain** [comment]
Didn't realized this the was "solutions" branch. I think the more important branch to be working on is the "tests" branch. So in that case, I'll deal with these minutiae changes I mentioned in my previous message, so you can focus on working through the remaining chapters.

**Comment by oldfartdeveloper** [comment]
@milesfrain I'll leave it up to you on whether to use my PR here.  I'll put my `ch6-tests` branch changes into a separate PR.

**Comment by milesfrain** [comment]
I incorporated your changes into https://github.com/purescript-contrib/purescript-book/pull/100

**Pull request closed without merging**
